server:
  port: 8079
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: order:ru.nedorezova.notificationservice.entity.Order